# -*- coding: utf-8 -*-
"""diabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BwYPebPEZwtcmnuFgjsdDnWnAY7GLJRK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as pl
import random as rn

ddf = pd.read_csv("diabetes.csv")

print(ddf.head(10))
#Printing first 10 values of diabetes.csv

print(ddf.info())
#Basic information about diabetes.csv

print(ddf.describe())
#Basic statistical details of diabetes.csv

print((ddf.describe()).T)
#Transpose of basic statistical details of diabetes.csv

ddf.loc[:, ["Glucose", "BloodPressure", "SkinThickness", "Insulin", "BMI"]] = ddf.replace(0, np.nan)
#Replacing '0' values in ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI'] as np.nan

for i in range(len(ddf.columns)):
  pl.hist(ddf.iloc[:, i], edgecolor="white", bins=15)
  pl.title(ddf.columns[i] + ", without cleaning NaN's")
  pl.xlabel("Values")
  pl.ylabel("Count")
  pl.show()
  #Plotting ddf as a histogram graph with 15 bins

ddf2 = ddf.copy()
#Making a copy of ddf
for col in ddf2.columns:
  total_NA = ddf2[col].isna().sum()
  if total_NA < 50:
    ddf2[col].fillna(ddf2.mean(), inplace=True)
    # If NaN number in a column is smaller than 50 (twice of bin number) ->
    # Fill the NaN's as "mean of it's column"
  else:
    probList = ddf2[col].value_counts(normalize=True).sort_index(ascending=True)
    #Creating a variable which holds the each value and its probability in ascending order
    for j in range(len(ddf2[col])):
      if(np.isnan(ddf2.loc[j, col])):
        weight_rand = rn.choices(probList.index, weights=probList.values)
        #Picking a random number from weighted values
        ddf2.loc[j, col] = weight_rand
    # If NaN number in a column is greater than 50 (twice of bin number) ->
    # Fill the NaN "randomly with weighted values"

for i in range(len(ddf2.columns)):
  pl.hist(ddf2.iloc[:, i], edgecolor="white", bins=15)
  ˆ
  pl.xlabel("Values")
  pl.ylabel("Count")
  pl.show()
  #Plotting ddf2 as a histogram graph with 15 bins
